Class DEV.Test.GrantTest Extends %Persistent
{

Storage Default
{
<Data name="GrantTestDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
</Data>
<DataLocation>^DEV.Test.GrantTestD</DataLocation>
<DefaultData>GrantTestDefaultData</DefaultData>
<IdLocation>^DEV.Test.GrantTestD</IdLocation>
<IndexLocation>^DEV.Test.GrantTestI</IndexLocation>
<StreamLocation>^DEV.Test.GrantTestS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
