Class DEV.Test.GrantTest2 Extends %Persistent
{

Storage Default
{
<Data name="GrantTest2DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
</Data>
<DataLocation>^DEV.Test.GrantTest2D</DataLocation>
<DefaultData>GrantTest2DefaultData</DefaultData>
<IdLocation>^DEV.Test.GrantTest2D</IdLocation>
<IndexLocation>^DEV.Test.GrantTest2I</IndexLocation>
<StreamLocation>^DEV.Test.GrantTest2S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
