Class DEV.GenericProduction Extends Ens.Production
{

XData ProductionDefinition
{
<Production Name="DEV.GenericProduction" LogGeneralTraceEvents="false">
  <Description></Description>
  <ActorPoolSize>2</ActorPoolSize>
  <Item Name="DEV.Test.SOAP.Prod.BS.Patient" Category="" ClassName="DEV.Test.SOAP.Prod.BS.Patient" PoolSize="0" Enabled="true" Foreground="false" Comment="" LogTraceEvents="false" Schedule="">
  </Item>
</Production>
}

}
